# Generated by Django 4.1.6 on 2023-02-23 07:49

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=300, verbose_name='Wallet Address')),
                ('wallet_barcode', models.ImageField(help_text='Upload an image of your wallet Barcode', upload_to='dhb/admin/', verbose_name='Wallet Barcode')),
                ('bank_name', models.CharField(max_length=300, verbose_name='Bank Name')),
                ('bank_account_name', models.CharField(max_length=300, verbose_name='Bank Account Name')),
                ('bank_account_number', models.IntegerField(verbose_name='Bank Account Number')),
                ('etherium_value_in_dollars', models.IntegerField(default=0)),
                ('bitcoin_value_in_dollars', models.IntegerField(default=0)),
                ('usdt_value_in_dollars', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Balance Type')),
                ('selected_asset', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Etherium', 'Etherium'), ('BankTransfer', 'BankTransfer'), ('Paypal', 'Paypal'), ('CashApp', 'CashApp')], max_length=200, verbose_name='Transaction Type')),
                ('ethereum_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ethereum Address')),
                ('bitcoin_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bitcoin Address')),
                ('account_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Name')),
                ('account_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Number')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Name')),
                ('swift_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Swift Code')),
                ('paypal_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paypal Email')),
                ('cashtag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cash Tag')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, default=core.utils.random_string, max_length=500, null=True)),
                ('balance_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Balance Type')),
                ('selected_asset', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Etherium', 'Etherium'), ('BankTransfer', 'BankTransfer'), ('Paypal', 'Paypal'), ('CashApp', 'CashApp')], max_length=200, verbose_name='Transaction Type')),
                ('ethereum_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ethereum Address')),
                ('bitcoin_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bitcoin Address')),
                ('account_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Name')),
                ('account_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Account Number')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank Name')),
                ('swift_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Swift Code')),
                ('paypal_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paypal Email')),
                ('cashtag', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cash Tag')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(blank=True, default=core.utils.random_string, max_length=500, null=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('transfer', 'transfer'), ('withdraw', 'withdraw')], max_length=200, verbose_name='Transaction Type')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transation_state', models.BooleanField(default=False)),
                ('selected_asset', models.CharField(blank=True, choices=[('Bitcoin', 'Bitcoin'), ('Etherium', 'Etherium'), ('BankTransfer', 'BankTransfer'), ('Paypal', 'Paypal'), ('CashApp', 'CashApp'), ('usdt', 'usdt')], max_length=200, null=True, verbose_name='Transaction Asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(blank=True, null=True, verbose_name='Account Number')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Name')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('bitcoin_address', models.CharField(blank=True, max_length=200, verbose_name='Bitcoin Address')),
                ('etherium_address', models.CharField(blank=True, max_length=200, verbose_name='Etherium Address')),
                ('cashtag', models.CharField(blank=True, max_length=200, null=True, verbose_name='CashTag')),
                ('swift_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Swift Code')),
                ('paypal_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Paypal Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
